# Generated by Django 4.1.1 on 2022-09-17 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0002_remove_menu_dishes_remove_menu_drinks_dish_menus_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="menus",
        ),
        migrations.RemoveField(
            model_name="drink",
            name="menus",
        ),
        migrations.AddField(
            model_name="menu",
            name="dishes",
            field=models.ManyToManyField(related_name="menus", to="restaurants.dish"),
        ),
        migrations.AddField(
            model_name="menu",
            name="drinks",
            field=models.ManyToManyField(related_name="menus", to="restaurants.drink"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
        ),
    ]
